version: '3.8'
services:
    nginx-server:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./webapp:/var/www/website
        depends_on:
            - php
    php:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./webapp:/var/www/website
    mysql-server:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: 'secret'
            MYSQL_USER: 'db_user'
            MYSQL_PASSWORD: 'secret'
            MYSQL_DATABASE: 'db_lemp_template'
            MYSQL_ROOT_HOST: 127.0.0.1
        volumes:
            - mysqldata:/var/lib/mysql
        ports:
            - 3306:3306
volumes:
    mysqldata: {}